# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://modmuss50.me/fabric.html
	minecraft_version=1.20.6
	yarn_mappings=1.20.6+build.3
	loader_version=0.15.11

# Mod Properties
	mod_version = 0.25.1+1.20.6
	maven_group = btwr
	archives_base_name = btwr-core

# Dependencies
	# check this on https://modmuss50.me/fabric.html
	fabric_version=0.100.8+1.20.6
	modmenu_version=10.0.0
	clothconfig_version=14.0.126


