{
  "formatVersion": "1.1",
  "component": {
    "group": "btwr",
    "module": "btwr-core",
    "version": "0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.1.118"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "btwr-core-0.22.jar",
          "url": "btwr-core-0.22.jar",
          "size": 1290796,
          "sha512": "dacc96f546affddf34bf2a6d29d14d008e3c9b070a42cfd169357cfb8afa622445455d2303f5f9a019f39deaecd41c66c16083422fff0035ad7f2598a7524ea8",
          "sha256": "2d0f8ec5a5d2d26c2aa7ec5d7649100e6e90a511c136f6c6a67f4c2c8148662b",
          "sha1": "1a6880368af2e1b34c4dc1f7cbb1b25b51a2a0a4",
          "md5": "b9f9df8ee622e9772c1badcd44af0237"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.1.118"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.0+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "btwr-core-0.22.jar",
          "url": "btwr-core-0.22.jar",
          "size": 1290796,
          "sha512": "dacc96f546affddf34bf2a6d29d14d008e3c9b070a42cfd169357cfb8afa622445455d2303f5f9a019f39deaecd41c66c16083422fff0035ad7f2598a7524ea8",
          "sha256": "2d0f8ec5a5d2d26c2aa7ec5d7649100e6e90a511c136f6c6a67f4c2c8148662b",
          "sha1": "1a6880368af2e1b34c4dc1f7cbb1b25b51a2a0a4",
          "md5": "b9f9df8ee622e9772c1badcd44af0237"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "btwr-core-0.22-sources.jar",
          "url": "btwr-core-0.22-sources.jar",
          "size": 1313532,
          "sha512": "412333ffcdbd366055b426a078fd45a3fccf6d8bcc47118c4e8a95cc94f5c58c47ff030ea25ec48e9cce4ddcc5906cabdc047b28f6e284d45a9a5b767b539d36",
          "sha256": "573990e2c0e302d84c4a4de66b100cf4bd8a59bfaae5498c3c07c3c0c4827567",
          "sha1": "567d6ddcfefecde658c768874ea6f84f85b63da4",
          "md5": "f8d94f01e8142fb9413e576097112087"
        }
      ]
    }
  ]
}
